export const CHECK_CONNECT = "CHECK_CONNECT";

export const CHECK_CONNECT_ACTION = "CHECK_CONNECT_ACTION";

export const REQUEST_SERVICE_DATA = "REQUEST_SERVICE_DATA";

export const REQUEST_SCRIPT_DATA = "REQUEST_SCRIPT_DATA";

export const REQUEST_DATA_COUNT = "REQUEST_DATA_COUNT";

export const CHECK_CONNECT_POPUP = "CHECK_CONNECT_POPUP";

export const LONG_CONNECT_TO_POPUP = "LONG_CONNECT_TO_POPUP";

export const CONFIG_CHANGE = "CONFIG_CHANGE";

export const REQUEST_CONFIG_STORAGE = "REQUEST_CONFIG_STORAGE";

export const CHECK_TEST_MODE = "CHECK_TEST_MODE";

export const POPUP_HELPER = "POPUP_HELPER";
