export const SERVICE_TO_CONTENT = "SERVICE_TO_CONTENT";
export const CONTENT_TO_SERVICE = "CONTENT_TO_SERVICE";

export const CONTENT_TO_DOCUMENT = "CONTENT_TO_DOCUMENT";
export const DOCUMENT_TO_CONTENT = "DOCUMENT_TO_CONTENT";

export const SERVICE_TO_POPUP = "SERVICE_TO_POPUP";
export const POPUP_TO_SERVICE = "POPUP_TO_SERVICE";


export const MESSAGE_TYPE = "MESSAGE_TYPE";